# -*- coding: utf-8 -*-
{
    'name': 'Studio customizations',
    'version': '15.0.1.0',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': '',
    'depends': [
        'account',
        'account_accountant',
        'account_followup',
        'base',
        'contacts',
        'contacts_enterprise',
        'crm',
        'mail',
        'membership_sequence',
        'payment',
        'record_creation_survey',
        'sale',
        'sales_team',
        'survey',

    ],
    'data': [
        # 'views/crm_lead_inherit_view.xml',
        # 'security/ir.model.access.csv',
        # 'data/ir_model.xml',
        # 'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        # 'data/ir_actions_act_window_view.xml',
        # 'data/ir_actions_report.xml',
        # 'data/mail_template.xml',
        # 'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
        # 'data/ir_filters.xml',
        # 'data/base_automation.xml',
        # 'data/ir_model_access.xml',
        # 'data/ir_default.xml',
    ],
}
